# Generated by Django 3.1.7 on 2021-03-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210305_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('purchase_status', 'Purchase status'), ('promotions', 'Promotions'), ('new_products', 'New products'), ('new_coupons', 'New coupons'), ('new_setups', 'New setups')], default='a', max_length=70),
            preserve_default=False,
        ),
    ]
