# Generated by Django 3.1.7 on 2021-03-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='milestones',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('preparing_shipment', 'milestones'), ('on_the_way', 'On the way'), ('no_delivery_confirmation', 'No delivery confirmation'), ('delivery_refused', 'Delivery refused'), ('delivered', 'Delivered')], max_length=30)),
                ('observations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
