# Generated by Django 3.1.7 on 2021-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210305_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
