# Generated by Django 3.1.7 on 2021-03-05 06:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210305_0522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_collections_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
    ]
